name: facebook
description: basic facebook wrap for dart
version: 0.0.1
homepage: https://lefty.io
author: Kevin Segaud <kevin.segaud@gmail.com>


environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: 0.6.1
  dart_browser_loader: 0.0.4

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
